# Версия программного интерфейса Kubernetes
apiVersion: apps/v1
# Тип объекта
kind: Deployment
# Метаданные нашего объекта, вложенный объект ObjectMeta
metadata:
   # список меток канареечного развертывания
  labels:
    app: time-service
    release: canary
  name: time-service-canary
# Описание собственно правил развертывания контейнера
# Вложенный объект DeploymentSpec
spec:
  # Количество запущенных отсеков pods для масштабирования
  replicas: 1
  selector:
    matchLabels:
      app: time-service
      release: canary
   # описание шаблона для создания новых отсеков    
  template:
    metadata:
      # список меток для канареечных отсеков pods
      labels:
        app: time-service
        release: canary
    # непосредственно описание контейнера в отсеке    
    spec:
      containers:
      - image: ivanporty/time-service:0.2.0
        name: time-service

