apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weekend-service
  name: weekend-service
spec:
  selector:
    matchLabels:
      app: weekend-service
  template:
    metadata:
      labels:
        app: weekend-service
    spec:
      containers:
        name: weekend-service
        - readinessProbe:
             httpGet:
               path: /ready
               port: 5678
             periodSeconds: 2
             initialDelaySeconds: 5
             failureThreshold: 2
             successThreshold: 1
        - image: ivanporty/weekend-service:0.2.0
